version: "3.7"

x-django:
  &django
  build: ./backend
  restart: "on-failure"
  depends_on:
    - data-base
  environment:
    # django
    - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    - DJANGO_DEBUG=yes
    # postgres
    - POSTGRES_DB=${POSTGRES_DB}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_HOST=postgres-presintation
    - POSTGRES_PORT=${POSTGRES_PORT}

services:
  backend:
    <<: *django
    tty: true
    container_name: backend-presintation
    command: bash -c "python manage.py runserver 0.0.0.0:8000" # python manage.py migrate && etc.

  server:
    image: nginx:stable
    container_name: nginx-presintation
    restart: "on-failure"
    volumes:
      - ./server/nginx.conf:/etc/nginx/templates/nginx.conf.template
      - ./server/dev.nginx.conf:/etc/nginx/templates/presintation.conf.template
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
    ports:
      - 80:80
  data-base:
    image: postgres:11.7
    container_name: postgres-presintation
    restart: "on-failure"
    ports: 
     - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=postgres-presintation
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    container_name: frontend-presintation
    restart: "on-failure"
    depends_on:
    - backend
    command: node node_modules/vite/bin/vite.js preview --port 80 --host
volumes:
  db_data:
